# Generated by Django 2.0.4 on 2018-04-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form2',
            options={'verbose_name': 'Form2', 'verbose_name_plural': 'Forms2'},
        ),
    ]
